// Mocks generated by Mockito 5.4.4 from annotations
// in weather_info_app/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:convert' as _i12;
import 'dart:typed_data' as _i14;

import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:weather_info_app/core/api/base_client.dart' as _i11;
import 'package:weather_info_app/core/error/failure.dart' as _i7;
import 'package:weather_info_app/features/weather_info/data/data_source/weather_info_remote_data_source.dart'
    as _i10;
import 'package:weather_info_app/features/weather_info/data/model/weather_info_model.dart'
    as _i3;
import 'package:weather_info_app/features/weather_info/domain/entity/weather_info.dart'
    as _i8;
import 'package:weather_info_app/features/weather_info/domain/repository/weather_info_repository.dart'
    as _i9;
import 'package:weather_info_app/features/weather_info/domain/usecase/weather_info_usecase.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeatherInfoModel_1 extends _i1.SmartFake
    implements _i3.WeatherInfoModel {
  _FakeWeatherInfoModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_2 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_3 extends _i1.SmartFake
    implements _i4.StreamedResponse {
  _FakeStreamedResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherInfoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherInfoUseCase extends _i1.Mock
    implements _i5.WeatherInfoUseCase {
  MockWeatherInfoUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.WeatherInfo>?>> getWeatherInfo(
    String? latitude,
    String? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherInfo,
          [
            latitude,
            longitude,
          ],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i8.WeatherInfo>?>>.value(
                _FakeEither_0<_i7.Failure, List<_i8.WeatherInfo>?>(
          this,
          Invocation.method(
            #getWeatherInfo,
            [
              latitude,
              longitude,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i8.WeatherInfo>?>>);
}

/// A class which mocks [WeatherInfoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherInfoRepository extends _i1.Mock
    implements _i9.WeatherInfoRepository {
  MockWeatherInfoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.WeatherInfo>?>> getWeatherInfo(
    String? latitude,
    String? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherInfo,
          [
            latitude,
            longitude,
          ],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i8.WeatherInfo>?>>.value(
                _FakeEither_0<_i7.Failure, List<_i8.WeatherInfo>?>(
          this,
          Invocation.method(
            #getWeatherInfo,
            [
              latitude,
              longitude,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i8.WeatherInfo>?>>);
}

/// A class which mocks [WeatherInfoRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherInfoRemoteDataSource extends _i1.Mock
    implements _i10.WeatherInfoRemoteDataSource {
  MockWeatherInfoRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.WeatherInfoModel> getWeatherInfo(
    String? latitude,
    String? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherInfo,
          [
            latitude,
            longitude,
          ],
        ),
        returnValue:
            _i6.Future<_i3.WeatherInfoModel>.value(_FakeWeatherInfoModel_1(
          this,
          Invocation.method(
            #getWeatherInfo,
            [
              latitude,
              longitude,
            ],
          ),
        )),
      ) as _i6.Future<_i3.WeatherInfoModel>);
}

/// A class which mocks [BaseApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseApiClient extends _i1.Mock implements _i11.BaseApiClient {
  MockBaseApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<dynamic> get(String? url) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i4.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<_i4.Response>);

  @override
  _i6.Future<_i4.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<_i4.Response>);

  @override
  _i6.Future<_i4.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i4.Response>);

  @override
  _i6.Future<_i4.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i4.Response>);

  @override
  _i6.Future<_i4.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i4.Response>);

  @override
  _i6.Future<_i4.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i4.Response>);

  @override
  _i6.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<_i14.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i14.Uint8List>.value(_i14.Uint8List(0)),
      ) as _i6.Future<_i14.Uint8List>);

  @override
  _i6.Future<_i4.StreamedResponse> send(_i4.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i6.Future<_i4.StreamedResponse>.value(_FakeStreamedResponse_3(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i6.Future<_i4.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
